import java.awt.Component;
import java.sql.*;
import java.util.Scanner;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;






//date
import java.util.Date;  

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Registration extends javax.swing.JFrame {
    private String c_num;
    private String c_name;
    private String c_pwd;
    private String c_acc;
    private String c_cash;
    
    
    private Component frame;
    

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        getNumber();
        getAccount();
        this.c_pwd = getToday();
    }

    
    
    private void getNumber() {
        
        int rand = (int) (Math.random() * 98999999) + 1000000;
        this.c_num = Integer.toString(rand);
        NumberField.setText(this.c_num);
       
    }
    
    private void getAccount(){
                
        long detail = System.currentTimeMillis() / 1000;
        //long details = now.getTime()/1000;
        Long IntDetail = Long.valueOf(this.c_num);
        Long data =  detail + IntDetail;
        this.c_acc = "DP"+ data;
        AccountField.setText(this.c_acc);
    }
    
    private String getToday(){
        Date d=new Date();
        int year  =  d.getYear() - 100;
        String pwd = ""+ d.getDate();
        pwd += "" +d.getMonth();
        pwd += "" +year;
        return pwd;
        
    }
    
    private void clearFields(){
        
        rNameField.setText("");
	rCashField.setText("");
	AccountField.setText("");
	NumberField.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistrationTextLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        NumberLabel = new javax.swing.JLabel();
        AccountLabel = new javax.swing.JLabel();
        rNameField = new javax.swing.JTextField();
        CashLabel = new javax.swing.JLabel();
        rCashField = new javax.swing.JTextField();
        AddClientButton = new javax.swing.JButton();
        AddClientButton1 = new javax.swing.JButton();
        AccountField = new javax.swing.JLabel();
        NumberField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RegistrationTextLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RegistrationTextLabel.setText("Registration");

        NameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NameLabel.setText("Name");

        NumberLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NumberLabel.setText("Number");

        AccountLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AccountLabel.setText("Account");

        rNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNameFieldActionPerformed(evt);
            }
        });

        CashLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CashLabel.setText("Cash");

        rCashField.setText("0.00");
        rCashField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rCashField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCashFieldActionPerformed(evt);
            }
        });

        AddClientButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddClientButton.setText("Add");
        AddClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClientButtonActionPerformed(evt);
            }
        });

        AddClientButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddClientButton1.setText("Menu");
        AddClientButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClientButton1ActionPerformed(evt);
            }
        });

        AccountField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NumberField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AccountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(CashLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rNameField)
                            .addComponent(rCashField)
                            .addComponent(AccountField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumberField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(RegistrationTextLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(AddClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddClientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegistrationTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(rNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AccountLabel)
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddClientButton)
                            .addComponent(AddClientButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AccountField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rCashField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rNameFieldActionPerformed

    private void rCashFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCashFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rCashFieldActionPerformed

    private void AddClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClientButtonActionPerformed
        // TODO add your handling code here:
        String pwd = "18082019";
        
        String url = "jdbc:mysql://localhost/bank_system";
        String username = "root";
        String password = "";
        Scanner scanner = new Scanner(System.in); 
             
        try (Connection conn = DriverManager.getConnection(url, username, password)){     
            String sql = "INSERT INTO users (FULLNAME, CLIENT_NUM, PASSWORD, ACCOUNT, CASH ) Values (?,?,?,?,?)";
                PreparedStatement preparedStatement = conn.prepareStatement(sql);
                preparedStatement.setString(1, rNameField.getText() );
                preparedStatement.setString(2, NumberField.getText() );
                preparedStatement.setString(3, this.c_pwd );
                preparedStatement.setString(4, AccountField.getText() );
                preparedStatement.setString(5, rCashField.getText() );

                 
                int rows = preparedStatement.executeUpdate();
                 
                System.out.printf("%d rows added", rows);;
                JOptionPane.showMessageDialog(frame, "User has been added");
                clearFields();
             } catch (SQLException ex) {
                JOptionPane.showMessageDialog(frame, "User has not been added");
                clearFields();
                System.out.println(ex);
                 
        }
   
    }//GEN-LAST:event_AddClientButtonActionPerformed

    private void AddClientButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClientButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddClientButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountField;
    private javax.swing.JLabel AccountLabel;
    private javax.swing.JButton AddClientButton;
    private javax.swing.JButton AddClientButton1;
    private javax.swing.JLabel CashLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NumberField;
    private javax.swing.JLabel NumberLabel;
    private javax.swing.JLabel RegistrationTextLabel;
    private javax.swing.JTextField rCashField;
    private javax.swing.JTextField rNameField;
    // End of variables declaration//GEN-END:variables
}
